SCREEN_TITLE = "I'M THE EVIL TWIN"
SPRITE_SCALING = 1
TILE_SCALING = 6
CHARACTER_SCALING = 1
MOVEMENT_SPEED = 5

SPRITE_IMAGE_SIZE = 32
SPRITE_SIZE = int(SPRITE_IMAGE_SIZE * SPRITE_SCALING)

SCREEN_WIDTH = SPRITE_SIZE * 30
SCREEN_HEIGHT = SPRITE_SIZE * 20

GRAVITY = 0.9
